//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1068 with alias "heroMedia"
	/// <summary>Hero media</summary>
	public partial interface IHeroMedia : IPublishedContent
	{
		/// <summary>Hero picker</summary>
		IPublishedContent HeroPicker { get; }

		/// <summary>Is video</summary>
		bool IsVideo { get; }
	}

	/// <summary>Hero media</summary>
	[PublishedContentModel("heroMedia")]
	public partial class HeroMedia : PublishedContentModel, IHeroMedia
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "heroMedia";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeroMedia(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroMedia, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hero picker: Choose video or image for header
		///</summary>
		[ImplementPropertyType("heroPicker")]
		public IPublishedContent HeroPicker
		{
			get { return GetHeroPicker(this); }
		}

		/// <summary>Static getter for Hero picker</summary>
		public static IPublishedContent GetHeroPicker(IHeroMedia that) { return that.GetPropertyValue<IPublishedContent>("heroPicker"); }

		///<summary>
		/// Is video: Click this if a video was chosen
		///</summary>
		[ImplementPropertyType("isVideo")]
		public bool IsVideo
		{
			get { return GetIsVideo(this); }
		}

		/// <summary>Static getter for Is video</summary>
		public static bool GetIsVideo(IHeroMedia that) { return that.GetPropertyValue<bool>("isVideo"); }
	}
}
