//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Info</summary>
	[PublishedContentModel("info")]
	public partial class Info : PublishedContentModel, IMetaBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "info";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Info(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Info, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About description: Write an about information text
		///</summary>
		[ImplementPropertyType("aboutDescription")]
		public IHtmlString AboutDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutDescription"); }
		}

		///<summary>
		/// About headline: Enter a headline for about description
		///</summary>
		[ImplementPropertyType("aboutHeadline")]
		public string AboutHeadline
		{
			get { return this.GetPropertyValue<string>("aboutHeadline"); }
		}

		///<summary>
		/// About pictures: Insert 4 images that belongs to about
		///</summary>
		[ImplementPropertyType("aboutPictures")]
		public IEnumerable<IPublishedContent> AboutPictures
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("aboutPictures"); }
		}

		///<summary>
		/// Contact description: Write a contact information text
		///</summary>
		[ImplementPropertyType("contactDescription")]
		public IHtmlString ContactDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("contactDescription"); }
		}

		///<summary>
		/// Contact form holder: Insert the contact form macro
		///</summary>
		[ImplementPropertyType("contactFormHolder")]
		public IHtmlString ContactFormHolder
		{
			get { return this.GetPropertyValue<IHtmlString>("contactFormHolder"); }
		}

		///<summary>
		/// Contact headline: Enter a headline for the contact description
		///</summary>
		[ImplementPropertyType("contactHeadline")]
		public string ContactHeadline
		{
			get { return this.GetPropertyValue<string>("contactHeadline"); }
		}

		///<summary>
		/// Contact submit test: Enter text for contact form submit button
		///</summary>
		[ImplementPropertyType("contactSubmitTest")]
		public string ContactSubmitTest
		{
			get { return this.GetPropertyValue<string>("contactSubmitTest"); }
		}

		///<summary>
		/// Map description: Write a map information text
		///</summary>
		[ImplementPropertyType("mapDescription")]
		public IHtmlString MapDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("mapDescription"); }
		}

		///<summary>
		/// Map headline: Enter a headline for map description
		///</summary>
		[ImplementPropertyType("mapHeadline")]
		public string MapHeadline
		{
			get { return this.GetPropertyValue<string>("mapHeadline"); }
		}

		///<summary>
		/// Map holder: Insert map macro
		///</summary>
		[ImplementPropertyType("mapHolder")]
		public IHtmlString MapHolder
		{
			get { return this.GetPropertyValue<IHtmlString>("mapHolder"); }
		}

		///<summary>
		/// Meta Description: This is the page description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaBase.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta Keywords: This is the page keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.MetaBase.GetMetaKeywords(this); }
		}

		///<summary>
		/// Meta Ttitle: This is the page title
		///</summary>
		[ImplementPropertyType("metaTtitle")]
		public string MetaTtitle
		{
			get { return Umbraco.Web.PublishedContentModels.MetaBase.GetMetaTtitle(this); }
		}

		///<summary>
		/// Hide in navigation?: Should this page be hidden from the navigation?
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.MetaBase.GetUmbracoNaviHide(this); }
		}
	}
}
