//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Masterclass</summary>
	[PublishedContentModel("masterclass")]
	public partial class Masterclass : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "masterclass";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Masterclass(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Masterclass, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// MasterClassBuyText: Text for the masterclass buy ticket button
		///</summary>
		[ImplementPropertyType("masterClassBuyText")]
		public string MasterClassBuyText
		{
			get { return this.GetPropertyValue<string>("masterClassBuyText"); }
		}

		///<summary>
		/// Masterclass description: Write a masterclass content description
		///</summary>
		[ImplementPropertyType("masterClassDescription")]
		public IHtmlString MasterClassDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("masterClassDescription"); }
		}

		///<summary>
		/// Masterclass description headline: Write a headline for the masterclass description
		///</summary>
		[ImplementPropertyType("masterClassDescriptionHeadline")]
		public string MasterClassDescriptionHeadline
		{
			get { return this.GetPropertyValue<string>("masterClassDescriptionHeadline"); }
		}

		///<summary>
		/// Masterclass information: Enter information about venue, date, time etc.
		///</summary>
		[ImplementPropertyType("masterClassInformation")]
		public IHtmlString MasterClassInformation
		{
			get { return this.GetPropertyValue<IHtmlString>("masterClassInformation"); }
		}

		///<summary>
		/// Masterclass speaker name: Name of the masterclass speaker
		///</summary>
		[ImplementPropertyType("masterClassSpeakerName")]
		public string MasterClassSpeakerName
		{
			get { return this.GetPropertyValue<string>("masterClassSpeakerName"); }
		}

		///<summary>
		/// Masterclass speaker picture: Insert a picture of the masterclass speaker
		///</summary>
		[ImplementPropertyType("masterClassSpeakerPicture")]
		public IPublishedContent MasterClassSpeakerPicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("masterClassSpeakerPicture"); }
		}
	}
}
