//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Session</summary>
	[PublishedContentModel("session")]
	public partial class Session : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "session";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Session(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Session, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Session date: Pick the session date
		///</summary>
		[ImplementPropertyType("sessionDate")]
		public string SessionDate
		{
			get { return this.GetPropertyValue<string>("sessionDate"); }
		}

		///<summary>
		/// Session description: Write a description for the session
		///</summary>
		[ImplementPropertyType("sessionDescription")]
		public IHtmlString SessionDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("sessionDescription"); }
		}

		///<summary>
		/// Session description headline: Enter headline for the session description
		///</summary>
		[ImplementPropertyType("sessionDescriptionHeadline")]
		public string SessionDescriptionHeadline
		{
			get { return this.GetPropertyValue<string>("sessionDescriptionHeadline"); }
		}

		///<summary>
		/// Session end time: Pick session end time
		///</summary>
		[ImplementPropertyType("sessionEndTime")]
		public string SessionEndTime
		{
			get { return this.GetPropertyValue<string>("sessionEndTime"); }
		}

		///<summary>
		/// Session presentation: Enter link to session presentation/slides
		///</summary>
		[ImplementPropertyType("sessionPresentation")]
		public string SessionPresentation
		{
			get { return this.GetPropertyValue<string>("sessionPresentation"); }
		}

		///<summary>
		/// Session speakers: Pick one or more speakers for this session
		///</summary>
		[ImplementPropertyType("sessionSpeakers")]
		public IEnumerable<IPublishedContent> SessionSpeakers
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("sessionSpeakers"); }
		}

		///<summary>
		/// Session start time: Pick session start time
		///</summary>
		[ImplementPropertyType("sessionStartTime")]
		public string SessionStartTime
		{
			get { return this.GetPropertyValue<string>("sessionStartTime"); }
		}

		///<summary>
		/// Session title: Enter the session title
		///</summary>
		[ImplementPropertyType("sessionTitle")]
		public string SessionTitle
		{
			get { return this.GetPropertyValue<string>("sessionTitle"); }
		}

		///<summary>
		/// Session venue: Pick the session venue
		///</summary>
		[ImplementPropertyType("sessionVenue")]
		public string SessionVenue
		{
			get { return this.GetPropertyValue<string>("sessionVenue"); }
		}

		///<summary>
		/// Session video: Enter link to session video
		///</summary>
		[ImplementPropertyType("sessionVideo")]
		public string SessionVideo
		{
			get { return this.GetPropertyValue<string>("sessionVideo"); }
		}
	}
}
