//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Speaker</summary>
	[PublishedContentModel("speaker")]
	public partial class Speaker : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "speaker";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Speaker(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Speaker, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Speaker description: Write text that describes the speaker
		///</summary>
		[ImplementPropertyType("speakerDescription")]
		public IHtmlString SpeakerDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("speakerDescription"); }
		}

		///<summary>
		/// Speaker description headline: Enter the title or description of the speaker
		///</summary>
		[ImplementPropertyType("speakerDescriptionHeadline")]
		public string SpeakerDescriptionHeadline
		{
			get { return this.GetPropertyValue<string>("speakerDescriptionHeadline"); }
		}

		///<summary>
		/// Speaker facebook: Enter speakers facebook link
		///</summary>
		[ImplementPropertyType("speakerFacebook")]
		public string SpeakerFacebook
		{
			get { return this.GetPropertyValue<string>("speakerFacebook"); }
		}

		///<summary>
		/// Speaker linkedin: Enter speakers linkedin link
		///</summary>
		[ImplementPropertyType("speakerLinkedin")]
		public string SpeakerLinkedin
		{
			get { return this.GetPropertyValue<string>("speakerLinkedin"); }
		}

		///<summary>
		/// Speaker name: Enter the speakers name
		///</summary>
		[ImplementPropertyType("speakerName")]
		public string SpeakerName
		{
			get { return this.GetPropertyValue<string>("speakerName"); }
		}

		///<summary>
		/// Speaker picture: Pick an image for the speaker
		///</summary>
		[ImplementPropertyType("speakerPicture")]
		public IPublishedContent SpeakerPicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("speakerPicture"); }
		}

		///<summary>
		/// Speaker twitter: Enter speakers twitter link
		///</summary>
		[ImplementPropertyType("speakerTwitter")]
		public string SpeakerTwitter
		{
			get { return this.GetPropertyValue<string>("speakerTwitter"); }
		}
	}
}
