//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Workshop</summary>
	[PublishedContentModel("workshop")]
	public partial class Workshop : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "workshop";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Workshop(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Workshop, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// What you learn: Describe what the attendees will learn from the workshop
		///</summary>
		[ImplementPropertyType("whatYouLearn")]
		public IEnumerable<string> WhatYouLearn
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("whatYouLearn"); }
		}

		///<summary>
		/// Workshop description: Write a description of the workshop
		///</summary>
		[ImplementPropertyType("workshopDescription")]
		public IHtmlString WorkshopDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("workshopDescription"); }
		}

		///<summary>
		/// Workshop headline: Enter a headline for the workshop
		///</summary>
		[ImplementPropertyType("workshopHeadline")]
		public string WorkshopHeadline
		{
			get { return this.GetPropertyValue<string>("workshopHeadline"); }
		}
	}
}
